-- enable-24-7-cron.sql  —  24/7 automation runbook (APPLIED 2026-07-01)
-- ---------------------------------------------------------------------------
-- STATUS: DONE. All jobs below are live. The platform runs its full lifecycle
-- loop 24/7 on mock data with MESSAGING_DRY_RUN=true, so nothing real is sent.
-- Verified live: the rota sweep returned providers:["dry-run"], notifiedStaff:5,
-- notifiedShifts:32, sendFailures:0; the drain + every sweep returned 200.
--
-- HOW THIS WAS APPLIED (note for next time): the app's Supabase connection is
-- read-only on the cron.job TABLE ("permission denied for table job"), so plain
-- `update cron.job ...` fails. BUT the cron.* FUNCTIONS are SECURITY DEFINER and
-- DO work from that role. Use them instead of table writes:
--     select cron.alter_job(job_id := <id>, active := true|false);
--     select cron.schedule('<name>', '<cron>', $$select public.trigger_app_cron('<path>')$$);
-- Gotcha: cron.schedule() on an EXISTING job updates schedule/command but keeps
-- the current active flag. To (de)activate, always use cron.alter_job.
-- No CRON_SECRET appears anywhere: it lives inside public.trigger_app_cron().
--
-- Current jobs (all active):
--   app-drain               */5   — sends queued messages (dry-run: no-ops)
--   app-sync-*              hourly — pull mock Dentally data
--   app-sweep-coordinator   */10
--   app-sweep-noshow        */10
--   app-sweep-reactivation  */10
--   app-sweep-recall        */10
--   app-sweep-speed-to-lead *      — every minute
--   app-sweep-reviews       */15  — no-ops until REVIEW_LINK_URL is set
--   app-sweep-rota          0 6   — daily 06:00 UTC; texts staff their shifts
-- ---------------------------------------------------------------------------

-- (Reference) the function-based equivalent of the original enable, in case the
-- jobs ever need re-enabling. jobids: reactivation=5, recall=6, noshow=7,
-- coordinator=10, speed-to-lead=11, rota=12, reviews=13.
-- select cron.alter_job(5, active := true);
-- select cron.alter_job(6, active := true);
-- select cron.alter_job(7, active := true);
-- select cron.alter_job(10, active := true);
-- select cron.alter_job(11, active := true);
-- select cron.alter_job(12, active := true);
-- select cron.alter_job(13, active := true);

-- ===========================================================================
-- GO LIVE FOR REAL (when the client is ready and real Dentally data is in):
--   1. Vercel prod env: set DENTALLY_API_KEY to the real key (currently mock),
--      set REVIEW_LINK_URL to the practice's Google review link.
--   2. Vercel prod env: set MESSAGING_DRY_RUN = false  (this is the switch that
--      turns simulated sends into real SMS/email). Redeploy so it takes effect.
--   3. Watch: select jobname,status,return_message,start_time
--             from cron.job_run_details order by start_time desc limit 20;
-- ===========================================================================

-- PANIC / PAUSE ALL SENDING immediately (no deploy needed):
--   either flip dry-run back on in Vercel (set MESSAGING_DRY_RUN=true, redeploy),
--   or pause the sweeps right now:
-- select cron.alter_job(j.jobid, active := false)
--   from cron.job j where j.jobname like 'app-sweep-%';
