-- register-anomaly-cron.sql  —  register the proactive anomaly pass on pg_cron
-- ---------------------------------------------------------------------------
-- STATUS: APPLIED (verify against cron.job).
--
-- This header used to deny that, and denied it for months while the job ran every
-- hour. A read-only `select jobname, schedule, active from cron.job` against
-- production on 4 September 2026 found 'app-sweep-anomaly' registered, active, on
-- `45 * * * *`, with 336 successful runs in cron.job_run_details, the last at
-- 18:45 UTC that day. Verify before acting on any header, including this one:
--
--   select jobname, schedule, active from cron.job where jobname = 'app-sweep-anomaly';
--
-- THE SCHEDULE BELOW WAS ALSO WRONG, AND THAT ONE COULD BITE. It said minute 40;
-- the live job runs at minute 45, and `cron.schedule()` on an existing job name
-- UPDATES it — so running this file as it stood would have quietly moved a job
-- that had been working for months, onto the same minute as the hourly Dentally
-- prewarm. Ruling W3/22 settles it in the live job's favour: cron.job is
-- authoritative, the file is corrected to :45, and nothing about the running job
-- changes. The statement below is therefore a harmless re-registration of what
-- already exists (identical name, schedule and command; cron.schedule keeps the
-- current active flag) — run it only to rebuild the job on a fresh project or
-- after somebody has unscheduled it.
--
-- Method, when it IS run: Fable applies cron SQL; the app's Supabase role is
-- read-only on the cron.job TABLE, so use the cron.* FUNCTIONS, which are
-- SECURITY DEFINER — the same method as supabase/ops/enable-24-7-cron.sql.
--
-- WHAT IT RUNS: /api/anomaly/sweep, which LOOKS and WRITES ONE TABLE.
--   It reads the dashboard's own assembled takings strip, the no-show risk
--   table, the speed-to-lead uncontacted-enquiry query, and bounded counts over
--   the per-module approval and outbox tables. It then writes rows to
--   anomaly_alert and nothing else. No patient record, no diary, no cadence, no
--   touch, no outbox, no message. There is no path from this job to a patient.
--
-- CADENCE: HOURLY, at minute 45.
--   Hourly rather than daily because two of the four conditions are perishable:
--   an enquiry uncontacted for an hour and a cluster of no-show risks in
--   TOMORROW's diary are both worth knowing about the same working day, and a
--   once-a-morning job would routinely be eleven hours late on them. Hourly
--   rather than */10 because none of them are perishable by the minute, and the
--   takings read goes through the shared dashboard cache which is only worth
--   waking once an hour anyway.
--
--   The dedupe key is what makes an hourly job quiet rather than deafening: a
--   condition that persists is REFRESHED, not re-raised, so a takings dip that
--   lasts a fortnight is one row on the owner's feed for a fortnight, not 336.
--
-- MINUTE 45, which is what the live job actually runs on and what this file now
-- says. The lifecycle sweeps run on */10 (minutes 0, 10, 20, 30...), post-op
-- proposes :25, the Meta insights pull proposes the top of the hour, and the
-- hourly Dentally prewarm holds :40 — so :45 lands this job in a gap rather than
-- alongside the Dentally readers. The file used to propose :40, i.e. the prewarm's
-- own minute; whoever registered the job in production chose better.
--
-- DENTALLY COST: one dashboard read per hour, at BACKGROUND priority
-- (runWithDentallyPriority in src/lib/anomaly/collect.ts), and usually a cache
-- hit rather than a scan. A refusal from the shared budget guard is not an error
-- here: it produces an unavailable takings cell, the detector refuses, and the
-- run reports the refusal in its `refused` array rather than inventing a figure.
--
-- SAFE TO REGISTER BEFORE THE SYSTEM IS SWITCHED ON. 'anomaly-alerts' is
-- DEFAULT-OFF in the systems catalog, so until an owner deliberately enables it
-- every run returns {"ok":true,"skipped":"system off"} having made no read of
-- any kind — the switch is checked before the lease is even taken.
--
-- CRON_SECRET is NOT written here; it lives inside public.trigger_app_cron(),
-- exactly as the other jobs rely on.
-- ---------------------------------------------------------------------------

select cron.schedule(
  'app-sweep-anomaly',
  '45 * * * *',
  $$select public.trigger_app_cron('/api/anomaly/sweep')$$
);

-- cron.schedule() on an existing job named 'app-sweep-anomaly' updates its
-- schedule/command but KEEPS the current active flag. If it was ever created
-- inactive, activate it explicitly (find the id in cron.job first):
--   select cron.alter_job(job_id := (select jobid from cron.job
--                                    where jobname = 'app-sweep-anomaly'),
--                         active := true);

-- Verify after applying:
--   select jobname, schedule, active from cron.job where jobname = 'app-sweep-anomaly';
--   select jobname, status, return_message, start_time
--     from cron.job_run_details
--     where jobname = 'app-sweep-anomaly'
--     order by start_time desc limit 5;
--
-- A healthy run with the system OFF returns HTTP 200 and
-- {"ok":true,"skipped":"system off"} — that is the correct shipping state.
-- With it ON, the body carries {detected, raised, refreshed, held, resolved,
-- refused}. Read `refused` first: it names every reading the pass could not
-- prove, and a run with detected:0 and a long `refused` list is a blind pass,
-- not a quiet practice.

-- TO REMOVE:
--   select cron.unschedule('app-sweep-anomaly');
